name: ModFix
main: modfix.Main
version: 2.1.dev
author: Shevchik
depend: [ProtocolLib]
load: STARTUP
commands:
  modfix:
    usage: 'Используйте команд /modfix help для получения списка комманд'