name: ModFix
main: modfix.Main
version: 2.8
author: Shevchik
softdepend: [ProtocolLib]
load: STARTUP
commands:
  modfix:
    usage: 'Используйте команд /modfix help для получения списка комманд'